// Generates (a) src/lib/fixture.generated.ts from the Deel CSV fixture and (b) copies the pdf.js worker
// into public/ so it is served from our own origin. Both outputs are committed/ignored as noted in .gitignore.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const csv = readFileSync(join(root, "../../packages/ingest/fixtures/deel/synthetic-transactions.csv"), "utf8");
writeFileSync(
  join(root, "src/lib/fixture.generated.ts"),
  `// GENERATED by scripts/gen-assets.mjs. Do not edit.\nexport const DEEL_CSV = ${JSON.stringify(csv)};\n`,
);

const require = createRequire(import.meta.url);
const pdfjsDir = dirname(require.resolve("pdfjs-dist/package.json"));
mkdirSync(join(root, "public/pdfjs"), { recursive: true });
copyFileSync(join(pdfjsDir, "build/pdf.worker.min.mjs"), join(root, "public/pdfjs/pdf.worker.min.mjs"));
console.log("assets generated");
